### ISSUE TITLE
Needs Proxy Support

### ISSUE THREAD

**Issue by gayuser12** [onemanbuilds/SpotifyStreamingBot#1]
I Would Really Recommend Adding Proxy Support To The Bot Where A User Can Enter Proxies(Non-Auth/Auth) Preferably Non Auth Proxies Work Good With Selenium So I Would Recommend u Add Proxies Since Its More Useful In That Way. U Can Make It like A option to run it with proxy or proxyless! It Would Be Really Great if U Add This

**Comment by onemanbuilds** [comment]
hi now i added proxy support, i don't have much time to test so if you got any issues feel free to contact me again.
