### ISSUE TITLE
Opens More Windows Then Required

### ISSUE THREAD

**Issue by gayuser12** [onemanbuilds/SpotifyStreamingBot#2]
It Opens Multiple Windows When Proxies Are Added Like if I enter 5 it opens more like every time now idk Why Maybe Its Because The Proxy Fails And Then It Retries But Instead Of Closing One Window It Opens A New One! Also Do U Have Any Social Media Platform Where i Can Contact U And Not Always Make Issues

**Comment by onemanbuilds** [comment]
I will check that when i have some time, also im availabla at discord onemanbuilds#2108 and i have a discord server which you can find in my videos description. There you can suggest features/apps and report issues
