### ISSUE TITLE
Doesn't press play button

### ISSUE THREAD

**Issue by ph44nt00m** [onemanbuilds/SpotifyStreamingBot#3]
when i start it it doesn't press play button and it shuts down after 15.20 seconds
the play button in the middle keeps turning but the music doesn't start

**Comment by onemanbuilds** [comment]
Today i will check that

**Comment by jlaf2020** [comment]
try again to do it by class like the first version that still working!! By the way, excellent job on the script... The logic it's perfect, and the new functions added are great...

**Comment by onemanbuilds** [comment]
@jlaf2020 thank you for the suggestions i will check them when i will have some freetime

**Comment by jlaf2020** [comment]
Thank you for the response, as matter of fact the play button its working
when you put a song link, not a playlist, but the problem it's that the
browser not become opened for a long time, independent of the timer set...
I made the wait time on driver wait a little longer and keeps opened for a
little extra time, but not the timer time... Your script is great!
Congrats!

Em qua, 4 de nov de 2020 01:37, onemanbuilds <notifications@github.com>
escreveu:

**Comment by onemanbuilds** [comment]
When do you have an error, like on the login page or when it is pressing the play button? Maybe i messed up something with the waits,so it isn't find something so it is closing, also i updated all of the requirements with the suggested pipreqs library.

**Comment by jlaf2020** [comment]
It was a random behavior with the play button when you give a playlist,
instead of a track URL. I think you right about the wait question, I'm
trying to figure out how to make the timer works, maybe the wait cloud be
the timer valeu.?

Em qua, 4 de nov de 2020 02:03, onemanbuilds <notifications@github.com>
escreveu:

**Comment by onemanbuilds** [comment]
Check it now

**Comment by jlaf2020** [comment]
It's working like a charm, one thing that we have to keep in mind it's that
windows defender it's already classifying the script in exe format
as a virus.... But who cares about windows defender .... Great job !!!

Em qua., 4 de nov. de 2020 às 03:32, onemanbuilds <notifications@github.com>
escreveu:

**Comment by onemanbuilds** [comment]
Thanks for your detailed responses now im closing the issue, have fun 👍
