### ISSUE TITLE
after placing the playlist it closes without any warning

### ISSUE THREAD

**Issue by alamaxjashek** [onemanbuilds/SpotifyStreamingBot#9]
I try to play songs, after the playlist closes itself without showing any warning. Noplay the songs.

 Attached the img. (the user atch was cleared)
![issue](https://user-images.githubusercontent.com/70828410/99034243-1af96f80-2553-11eb-9c73-989573b26bf0.png)

**Comment by onemanbuilds** [comment]
Yes i know there are issues with the spotify streaming bot at the moment. Thanks for your response.

**Comment by liveftb** [comment]
Onemanbuilds help me set it up please i need this asap
